name: Selenium WebDriver CI

# Trigger on push and pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Cache Maven dependencies (this speeds up the build)
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Maven and run tests
      - name: Run Maven tests
        run: mvn clean test

      # Step 5: Upload test results as artifacts (optional)
      - name: Upload TestNG Results
        uses: actions/upload-artifact@v2
        with:
          name: testng-results
          path: target/test-classes/testng-results.xml

      # Step 6: Optionally, you can integrate with Allure for nice reports
      # - name: Generate Allure Report
      #   run: allure serve target/allure-results
