name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Set up Maven
      - name: Check Maven version
        run: mvn -v

      # Install dependencies
      - name: Install dependencies
        run: mvn clean install

      # Run tests with Maven
      - name: Run Selenium tests
        run: mvn test

      # Upload test results to GitHub Actions
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
